[package]
name = "na"
version = "0.2.0"
edition = "2018"
authors = ["coddiw0mple"]
description = """
Sodium: A modern vi-like editor
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
unicode-segmentation = "*"
